name: Go
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: golangci/golangci-lint-action@v2
        with:
          version: v1.39

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.2'
      - uses: actions/checkout@v2
      - name: Go Test
        run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...
      - uses: codecov/codecov-action@v1.3.2
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./coverage.txt
